baseURL = "/"
languageCode = "es-es"
title = "Mujeres indígenas en la frontera"
defaultContentLanguage = "es"

[languages]
  [languages.es]
    languageName = "Español"
    weight = 1
    contentDir = "content/es"
  [languages.wayuunaiki]
    title = "Título en wayuunaiki"
    languageName = "Wayuunaiki"
    weight = 2
    contentDir = "content/wayuunaiki"
  [languages.tikuna]
    title = "Título en tikuna"
    languageName = "Tikuna"
    weight = 3
    contentDir = "content/tikuna"
  [languages.dulegaya]
    title = "Título en dulegaya"
    languageName = "Dulegaya"
    weight = 4
    contentDir = "content/dulegaya"