baseURL = "/"
languageCode = "es-es"
title = "Mujeres indígenas en la frontera"
defaultContentLanguage = "es"

[languages]
  [languages.es]
    languageName = "Español"
    weight = 1
    contentDir = "content/es"
  [languages.wayuu]
    languageName = "Wayuunaiki"
    weight = 2
    contentDir = "content/wayuu"
    title = "Título en Wayuu"
  [languages.tikuna]
    languageName = "Tikuna"
    weight = 3
    contentDir = "content/tikuna"
    title = "Título en Tikuna"
  [languages.guna]
    languageName = "Guna"
    weight = 4
    contentDir = "content/guna"
    title = "Título en Guna"