baseURL = "https://datasketch.github.io/mujer-palabra-resistencia/"
languageCode = "es-es"
title = "Mujeres, palabra, resistencia"
defaultContentLanguage = "es"
publishDir="docs"

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.blackFriday]
    hrefTargetBlank = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Inicio"
    weight = 1
    url = "/"
  [[menu.main]]
    identifier = "about"
    name = "Sobre la iniciativa"
    weight = 2
    url = "/sobre-la-iniciativa/"
  [[menu.main]]
    identifier = "wayuu"
    name = "Pueblo Wayuu"
    weight = 3
    url = "/pueblo-wayuu/"
  [[menu.main]]
    identifier = "gunadule"
    name = "Pueblo Gunadule"
    weight = 4
    url = "/pueblo-gunadule/"
  [[menu.main]]
    identifier = "tikuna"
    name = "Pueblo Tikuna"
    weight = 5
    url = "/pueblo-tikuna/"
  [[menu.main]]
    identifier = "opendata"
    name = "Repositorio de datos"
    weight = 6
    url = "/repositorio-de-datos/"

[languages]
  [languages.es]
    languageName = "Español"
    weight = 1
    contentDir = "content/es"
  [languages.wayuunaiki]
    languageName = "Wayuunaiki"
    weight = 2
    contentDir = "content/wayuunaiki"
  [languages.tikuna]
    languageName = "Tikuna"
    weight = 3
    contentDir = "content/tikuna"
  [languages.dulegaya]
    languageName = "Dulegaya"
    weight = 4
    contentDir = "content/dulegaya"